server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  logger:
  path: "./log/run"
  file: "{Y-m-d}.log"
  level: "all"
  stdout: false
proxy:
  url: "http://43.130.233.13:8000"

discord:
  trigger_url: "https://discord.com/api/v9/interactions"
  #token值，目前是静态的
  user_token: ""
  #服务器id
  guild_id: "1194298259775164506"
  #频道id
  channel_id: "1194298259775164510"
  application_id: "936929561302675456"
  session_id: "75346408b9c2878e8f4b75711dffa7b4"
  #mj 版本,这个可能会变，要实时关注
  version: "1237876415471554623"
  id: "938956540159881230"
